package service

import (
	"fmt"
	"regexp"
	"strings"
	"testing"
)

// Sister-repo contract tests.
//
// These pin the wire-format contracts that this repo *exposes* and
// other repos (excalibase-graphql, excalibase-auth, excalibase-watcher-go)
// *consume*. When one of these tests breaks, a sister repo will break
// in production — fix the test by updating both sides, never just
// here.
//
// Contracts covered:
//   1. ProjectID format: "proj-" + 10-char [a-z0-9] (used as K8s ns,
//      vault path segment, NATS subject component, URL path,
//      Postgres role name fragment)
//   2. Vault paths the auth-service reads (pki/signing/* + JWT KIDs)
//   3. NATS CDC subject pattern: "cdc.{projectId}.*" — flat namespace,
//      projectId is the only opaque token, no orgSlug prefix
//   4. PgDog config table column shape (consumed by PgDog operator)
//
// Any of these wire-shape decisions should land in CLAUDE.md / a
// project memory before the test changes — see
// project_identifier_convention.md and project_cdc_tenant_isolation.md
// in ~/.claude/projects/.../memory/.

const (
	// ProjectIDRE — generated by `service.generateProjectRef()`.
	// Used everywhere the projectId is part of an external identifier:
	// K8s namespaces, vault paths, NATS subjects, REST URLs.
	projectIDPatternStr = `^proj-[a-z0-9]{10}$`
	// Watcher's CDC stream subject pattern. graphql subscribes to
	// `cdc.{projectId}.>`. If this changes, the watcher's
	// publish-side and graphql's subscribe-side both break.
	cdcSubjectPattern = "cdc.%s.>"
	// JWT signing keypair location in vault. The auth service reads
	// these to mint per-project tokens; this repo reads the public
	// half to verify them on edge-function invokes.
	jwtPublicVaultPath  = "pki/signing/public"
	jwtPrivateVaultPath = "pki/signing/private"
)

func TestContract_ProjectID_FormatStable(t *testing.T) {
	re := regexp.MustCompile(projectIDPatternStr)
	for i := 0; i < 100; i++ {
		got := generateProjectRef()
		if !re.MatchString(got) {
			t.Fatalf("generated projectRef %q doesn't match %q", got, projectIDPatternStr)
		}
		if !strings.HasPrefix(got, "proj-") {
			t.Errorf("must keep proj- prefix (sister repos pattern-match on this): %q", got)
		}
		if len(got) != len("proj-")+10 {
			t.Errorf("length must stay 15 (5 prefix + 10 alphabet): got len=%d for %q", len(got), got)
		}
	}
}

func TestContract_ProjectID_DNSCompliant(t *testing.T) {
	// projectIds are used directly as Kubernetes namespace names AND
	// as PgDog config row primary keys, so they must be DNS-1123
	// label compliant: lowercase alphanumeric + dash, ≤63 chars,
	// must start AND end with alphanumeric.
	dns1123 := regexp.MustCompile(`^[a-z0-9]([a-z0-9-]*[a-z0-9])?$`)
	for i := 0; i < 50; i++ {
		got := generateProjectRef()
		if !dns1123.MatchString(got) {
			t.Errorf("projectRef %q is not DNS-1123 compliant — would fail K8s namespace creation", got)
		}
		if len(got) > 63 {
			t.Errorf("projectRef %q exceeds 63 chars (DNS label limit)", got)
		}
	}
}

func TestContract_VaultPath_Shape(t *testing.T) {
	// Pinned in project_identifier_convention.md: vault paths are
	// org-scoped {orgSlug} / projectId / details. Auth, edge functions,
	// and backup-cred lookups all assume this shape.
	cases := []struct {
		role string
		want string
	}{
		{"app", "projects/proj-abc1234567/credentials/app"},
		{"admin", "projects/proj-abc1234567/credentials/admin"},
		{"excalibase_app", "projects/proj-abc1234567/credentials/excalibase_app"},
	}
	projectID := "proj-abc1234567"
	for _, c := range cases {
		got := vaultCredentialPath(projectID, c.role)
		if got != c.want {
			t.Errorf("role=%s: got %q, want %q (sister-repo lookup will fail)", c.role, got, c.want)
		}
	}
}

func TestContract_NATS_CDCSubjectShape(t *testing.T) {
	// Watcher publishes on `cdc.{projectId}.{schema}.{table}`. graphql
	// subscribes to `cdc.{projectId}.>`. These two strings must agree
	// on the projectId component. Format pinned here so any rename of
	// the projectId variable doesn't silently change the subject
	// shape graphql consumes.
	projectID := generateProjectRef()
	got := fmt.Sprintf(cdcSubjectPattern, projectID)
	if !strings.HasPrefix(got, "cdc.") {
		t.Errorf("subject must start with cdc.: %q", got)
	}
	if !strings.Contains(got, projectID) {
		t.Errorf("subject must embed the projectId: %q (projectId=%s)", got, projectID)
	}
	if strings.Count(got, ".") < 2 {
		t.Errorf("subject must have at least two dots (cdc + projectId + suffix): %q", got)
	}
}

func TestContract_NATS_NoOrgSlug(t *testing.T) {
	// Pinned in project_cdc_tenant_isolation.md: the CDC subject
	// drops the orgSlug. ProjectId is the only tenant token; the
	// JWT scopes the WS subscription. Adding orgSlug back would
	// require a coordinated change in graphql's subscription
	// handling.
	projectID := generateProjectRef()
	got := fmt.Sprintf(cdcSubjectPattern, projectID)
	parts := strings.Split(got, ".")
	if len(parts) < 3 {
		t.Fatalf("unexpected subject shape: %q", got)
	}
	if parts[0] != "cdc" {
		t.Errorf("first segment must be 'cdc': %q", parts[0])
	}
	if parts[1] != projectID {
		t.Errorf("second segment must be projectId, not orgSlug: got %q want %q", parts[1], projectID)
	}
}

func TestContract_PgDogReloadSubject(t *testing.T) {
	// PgDog subscribes to "pgdog.config.reload" (per the fork's
	// config-reload-on-NATS feature). If this changes, the deployed
	// PgDog won't pick up changes to pgdog_databases / pgdog_users.
	if pgdogReloadSubject != "pgdog.config.reload" {
		t.Errorf("pgdog reload subject changed: got %q — must coordinate with pgdog fork before merging", pgdogReloadSubject)
	}
}

func TestContract_JWTPaths_Stable(t *testing.T) {
	// excalibase-auth (sister repo) reads these vault paths to load
	// the signing keypair. This repo reads jwtPublicVaultPath to
	// verify edge-function invokes. Renaming requires a coordinated
	// release of both repos.
	if jwtPublicVaultPath != "pki/signing/public" {
		t.Errorf("public key path changed: got %q — auth-service still reads pki/signing/public", jwtPublicVaultPath)
	}
	if jwtPrivateVaultPath != "pki/signing/private" {
		t.Errorf("private key path changed: got %q — auth-service still writes pki/signing/private", jwtPrivateVaultPath)
	}
}
