package service

import (
	"context"
	"errors"
	"strings"
	"testing"

	"github.com/excalibase/provisioning-poc/internal/domain"
	"github.com/excalibase/provisioning-poc/internal/k8s"
	"github.com/excalibase/provisioning-poc/internal/provisioner"
	"github.com/excalibase/provisioning-poc/internal/storage"
	"github.com/excalibase/provisioning-poc/internal/testutil/fakestore"
)

// victimProject is a project owned by an org the restoring caller is not a
// member of. Every field a takeover would rewrite carries a recognisable value.
func victimProject() *domain.DatabaseInstance {
	port := 5432
	return &domain.DatabaseInstance{
		ProjectID:      "proj-victim01",
		ProjectName:    "victim",
		OrgID:          "org-victim",
		OwnerID:        "user-victim",
		Namespace:      "org-victim-proj-victim01",
		DeploymentMode: domain.ModeK8s,
		Host:           "proj-victim01-postgres-rw.org-victim.svc.cluster.local",
		Port:           &port,
		DatabaseName:   "appdb",
		Username:       "victim_admin",
		Password:       "victim-password",
		Status:         "ACTIVE",
	}
}

// A restore must never be able to name an existing project as its target:
// the id is generated by the platform and a collision is refused before any
// side effect. Reproduces EXC-415 — admin of one org restoring onto another
// org's project id.
func TestRestoreNeverRepointsAnExistingProject(t *testing.T) {
	store, err := storage.NewFileSystemStore(t.TempDir())
	if err != nil {
		t.Fatalf("store: %v", err)
	}
	victim := victimProject()
	if err := store.Create(victim); err != nil {
		t.Fatalf("seed victim: %v", err)
	}
	source := &domain.DatabaseInstance{
		ProjectID: "proj-attacker", OrgID: "org-attacker",
		Namespace: "org-attacker-proj-attacker", Status: "ACTIVE",
	}
	if err := store.Create(source); err != nil {
		t.Fatalf("seed source: %v", err)
	}

	mock := k8s.NewMockClient()
	// The production registration path with no vault and no way to exec SQL,
	// so RegisterProject reduces to persisting the project row — the step
	// that must never repoint an existing project.
	registrar := NewProvisioningService(store, provisioner.NewFactory(), nil)
	adapter := newRestoreReadyAdapter(t, mock, registrar)
	adapter.SetInstanceStore(store)

	// A caller cannot name the target id, so this is the strongest form of
	// the attack: the generated id is forced to the victim's.
	resp, err := adapter.Restore(context.Background(), source,
		domain.RestoreRequest{NewProjectName: "victim", TargetProjectID: victim.ProjectID})
	if err == nil {
		t.Errorf("restore onto an existing project id must fail, got project %q", resp.ProjectID)
	}

	got, err := store.FindByProjectID(victim.ProjectID)
	if err != nil || got == nil {
		t.Fatalf("victim row: %v", err)
	}
	if got.OrgID != victim.OrgID {
		t.Errorf("victim org moved: got %q, want %q", got.OrgID, victim.OrgID)
	}
	if got.Host != victim.Host {
		t.Errorf("victim host repointed: got %q, want %q", got.Host, victim.Host)
	}
	if got.Username != victim.Username || got.Password != victim.Password {
		t.Errorf("victim credentials overwritten: %q/%q", got.Username, got.Password)
	}
	if _, created := mock.Namespaces["org-attacker-"+victim.ProjectID]; created {
		t.Error("no namespace may be created for a target id that already exists")
	}
}

// RegisterProject creates a project row; it must refuse an id that is already
// taken rather than rewriting the existing row.
func TestRegisterProjectRefusesAnExistingProjectID(t *testing.T) {
	store, err := storage.NewFileSystemStore(t.TempDir())
	if err != nil {
		t.Fatalf("store: %v", err)
	}
	victim := victimProject()
	if err := store.Create(victim); err != nil {
		t.Fatalf("seed victim: %v", err)
	}

	svc := NewProvisioningService(store, provisioner.NewFactory(), nil)
	err = svc.RegisterProject(context.Background(), &domain.DatabaseInstance{
		ProjectID: victim.ProjectID, OrgID: "org-attacker",
		Host: "attacker-rw", Username: "attacker", Password: "attacker-password",
	}, RegistrationOptions{})
	if err == nil {
		t.Error("registering an already-registered project id must fail")
	}

	got, _ := store.FindByProjectID(victim.ProjectID)
	if got.OrgID != victim.OrgID || got.Host != victim.Host || got.Password != victim.Password {
		t.Errorf("victim row was rewritten: org=%q host=%q", got.OrgID, got.Host)
	}
}

// Provisioning generates the project id too: a request can only ask for a
// display name, so it can never land on an existing project's row.
func TestProvisionCannotNameAnExistingProject(t *testing.T) {
	svc, store, _ := setupProvisioningTest(t)
	victim := victimProject()
	if err := store.Create(victim); err != nil {
		t.Fatalf("seed victim: %v", err)
	}

	resp, err := svc.Provision(context.Background(), domain.ProvisioningRequest{
		ProjectName: victim.ProjectID, OrgID: "org-attacker",
		DBType: domain.PostgreSQL, Tier: domain.Free,
	})
	if err != nil {
		t.Fatalf("Provision: %v", err)
	}
	if resp.ProjectID == victim.ProjectID {
		t.Fatal("a provision request must not be able to name an existing project id")
	}

	got, _ := store.FindByProjectID(victim.ProjectID)
	if got.OrgID != victim.OrgID || got.Host != victim.Host {
		t.Errorf("victim row was rewritten: org=%q host=%q", got.OrgID, got.Host)
	}
}

// failingCreateStore accepts every lookup but refuses to register anything, so
// tests can drive the "the row could not be written" branch.
type failingCreateStore struct {
	storage.InstanceStore
	err error
}

func (s failingCreateStore) Create(*domain.DatabaseInstance) error { return s.err }

func (s failingCreateStore) FindByProjectID(string) (*domain.DatabaseInstance, error) {
	return nil, nil
}

// Project id allocation fails loudly rather than handing back a guess.
func TestAllocateProjectIDFailsRatherThanGuessing(t *testing.T) {
	if _, err := allocateProjectID(nil); err == nil {
		t.Error("allocation without a store must fail")
	}

	lookupBroken := fakestore.NewInstances()
	lookupBroken.Err = errors.New("platform db down")
	if _, err := allocateProjectID(lookupBroken); err == nil {
		t.Error("allocation must fail when project id availability cannot be checked")
	}

	ref, err := allocateProjectID(fakestore.NewInstances())
	if err != nil {
		t.Fatalf("allocate: %v", err)
	}
	if !strings.HasPrefix(ref, "proj-") {
		t.Errorf("generated project id: %q", ref)
	}
}

// The gate every restore adapter runs before its first side effect.
func TestAssertProjectIDAvailable(t *testing.T) {
	store := fakestore.NewInstances()
	if err := store.Create(victimProject()); err != nil {
		t.Fatalf("seed: %v", err)
	}

	if err := assertProjectIDAvailable(store, ""); !errors.Is(err, ErrTargetProjectIDMissing) {
		t.Errorf("unallocated id: got %v, want ErrTargetProjectIDMissing", err)
	}
	if err := assertProjectIDAvailable(nil, "proj-free00001"); err == nil {
		t.Error("without a store the availability of an id is unknown; that must fail")
	}
	if err := assertProjectIDAvailable(store, victimProject().ProjectID); !errors.Is(err, ErrProjectIDTaken) {
		t.Errorf("taken id: got %v, want ErrProjectIDTaken", err)
	}
	if err := assertProjectIDAvailable(store, "proj-free00001"); err != nil {
		t.Errorf("a free id must pass: %v", err)
	}

	broken := fakestore.NewInstances()
	broken.Err = errors.New("platform db down")
	if err := assertProjectIDAvailable(broken, "proj-free00001"); err == nil {
		t.Error("a failed lookup must fail the restore, not be read as 'free'")
	}
}

// A restore that reaches the service without a platform-allocated id is
// refused — no adapter may invent one.
func TestRestoreFromBackupRequiresAnAllocatedTargetID(t *testing.T) {
	store := fakestore.NewInstances()
	if err := store.Create(&domain.DatabaseInstance{
		ProjectID: "proj-source01", OrgID: "org-a", DeploymentMode: domain.ModeK8s, Status: "ACTIVE",
	}); err != nil {
		t.Fatalf("seed: %v", err)
	}
	svc := NewBackupService(store, k8s.NewMockClient(), t.TempDir(), StaticBackupStorage(r2Storage()))

	_, err := svc.RestoreFromBackup(context.Background(), "proj-source01",
		domain.RestoreRequest{NewProjectName: "copy"})
	if !errors.Is(err, ErrTargetProjectIDMissing) {
		t.Fatalf("err: got %v, want ErrTargetProjectIDMissing", err)
	}

	ref, err := svc.AllocateProjectID()
	if err != nil {
		t.Fatalf("AllocateProjectID: %v", err)
	}
	if !strings.HasPrefix(ref, "proj-") || ref == "proj-source01" {
		t.Errorf("allocated id: %q", ref)
	}
}

// Provisioning surfaces both registration failures it can hit: no id to
// allocate, and a row that will not persist. Neither may produce a
// half-registered project.
func TestProvisionFailsWhenTheProjectCannotBeRegistered(t *testing.T) {
	req := domain.ProvisioningRequest{
		ProjectName: "external", OrgID: "org-a",
		DBType: domain.PostgreSQL, Tier: domain.Free,
	}

	lookupBroken := fakestore.NewInstances()
	lookupBroken.Err = errors.New("platform db down")
	svc := NewProvisioningService(lookupBroken, provisioner.NewFactory(), k8s.NewMockClient())
	if _, err := svc.Provision(context.Background(), req); err == nil {
		t.Error("provisioning must fail when no project id can be allocated")
	}

	svc = NewProvisioningService(
		failingCreateStore{InstanceStore: fakestore.NewInstances(), err: errors.New("platform db down")},
		provisioner.NewFactory(), k8s.NewMockClient())
	if _, err := svc.Provision(context.Background(), req); err == nil {
		t.Error("provisioning must fail when the project row cannot be written")
	}
}
