{{- if .Values.platformDB.backup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.platformDB.backup.s3Secret }}
  namespace: excalibase-platform
  labels:
    app.kubernetes.io/name: platform-db
    app.kubernetes.io/part-of: excalibase-platform
type: Opaque
data:
  ACCESS_KEY_ID: {{ required "platformDB.backup.s3AccessKeyID must be set" .Values.platformDB.backup.s3AccessKeyID | b64enc }}
  ACCESS_SECRET_KEY: {{ required "platformDB.backup.s3SecretAccessKey must be set" .Values.platformDB.backup.s3SecretAccessKey | b64enc }}
{{- end }}
