-- The restore target id is generated by the platform, so the display name
-- the caller asked for has to travel with the job to reach the restored
-- project row.
ALTER TABLE restore_jobs ADD COLUMN IF NOT EXISTS new_project_name TEXT NOT NULL DEFAULT '';
