package domain

import (
	"encoding/json"
	"fmt"
	"testing"
	"time"

	"github.com/excalibase/provisioning-poc/internal/testutil"
)

const (
	testDTODBName       = "test-db"
	testDTOMarshalFmt   = "marshal: %v"
	testDTOUnmarshalFmt = "unmarshal: %v"
	testDTORestoredName = "my-restored-project"
	testDTOProjID       = "proj-id-123"
	testDTOGetNewFmt    = "GetNewProject: got %q, want %q"
	testDTONameWins     = "name-wins"
)

func TestProvisioningRequestRoundTrip(t *testing.T) {
	req := ProvisioningRequest{
		ProjectName: testDTODBName,
		OrgID:       "org1",
		DBType:      PostgreSQL,
		Tier:        Standard,
		Backup:      &BackupSettings{Enabled: true, Schedule: "0 2 * * *", Retention: 30},
		Parameters:  map[string]string{"shared_preload_libraries": "pg_stat_statements"},
		Tags:        map[string]string{"env": "demo"},
	}

	b, err := json.Marshal(req)
	if err != nil {
		t.Fatalf(testDTOMarshalFmt, err)
	}

	var got ProvisioningRequest
	if err := json.Unmarshal(b, &got); err != nil {
		t.Fatalf(testDTOUnmarshalFmt, err)
	}

	if got.ProjectName != testDTODBName {
		t.Errorf("projectName: got %s, want test-db", got.ProjectName)
	}
	if got.DBType != PostgreSQL {
		t.Errorf("databaseType: got %s, want POSTGRESQL", got.DBType)
	}
	if got.Tier != Standard {
		t.Errorf("tier: got %s, want STANDARD", got.Tier)
	}
	if got.Backup == nil || !got.Backup.Enabled {
		t.Error("backup should be enabled")
	}
	if got.Parameters["shared_preload_libraries"] != "pg_stat_statements" {
		t.Error("parameters not preserved")
	}
}

func TestDatabaseMetricsNullFields(t *testing.T) {
	m := DatabaseMetrics{
		ProjectID:         testDTODBName,
		MetricsAvailable:  false,
		UnavailableReason: strPtr("Prometheus not reachable"),
	}

	b, err := json.Marshal(m)
	if err != nil {
		t.Fatalf(testDTOMarshalFmt, err)
	}

	var raw map[string]interface{}
	json.Unmarshal(b, &raw)

	// Null pointer fields should serialize as null
	if raw["cpuUsagePercent"] != nil {
		t.Errorf("cpuUsagePercent should be null, got %v", raw["cpuUsagePercent"])
	}
	if raw["activeConnections"] != nil {
		t.Errorf("activeConnections should be null, got %v", raw["activeConnections"])
	}
	if raw["metricsAvailable"] != false {
		t.Errorf("metricsAvailable should be false")
	}
	if raw["unavailableReason"] != "Prometheus not reachable" {
		t.Errorf("unavailableReason wrong: %v", raw["unavailableReason"])
	}
}

func TestDatabaseMetricsWithRealData(t *testing.T) {
	now := &FlexTime{Time: time.Now()}
	active := 3
	maxConn := 100
	m := DatabaseMetrics{
		ProjectID:         "duke-database",
		Timestamp:         now,
		MetricsAvailable:  true,
		ActiveConnections: &active,
		MaxConnections:    &maxConn,
		HealthStatus:      "HEALTHY",
	}

	b, _ := json.Marshal(m)
	var raw map[string]interface{}
	json.Unmarshal(b, &raw)

	if raw["activeConnections"] != float64(3) {
		t.Errorf("activeConnections: got %v", raw["activeConnections"])
	}
	if raw["maxConnections"] != float64(100) {
		t.Errorf("maxConnections: got %v", raw["maxConnections"])
	}
	if raw["metricsAvailable"] != true {
		t.Error("metricsAvailable should be true")
	}
	// CPU should still be null
	if raw["cpuUsagePercent"] != nil {
		t.Errorf("cpuUsagePercent should be null without metrics-server")
	}
}

func strPtr(s string) *string { return &s }

// --- RestoreRequest target project id ---

// The restore target id is generated by the platform. A body that names one
// must not reach the request: a caller who could pick it could point a restore
// at another tenant's project (EXC-415).
func TestRestoreRequestIgnoresACallerSuppliedProjectID(t *testing.T) {
	var r RestoreRequest
	body := `{"newProjectName":"` + testDTORestoredName + `","newProjectId":"` + testDTOProjID + `","targetProjectId":"` + testDTOProjID + `"}`
	if err := json.Unmarshal([]byte(body), &r); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if r.TargetProjectID != "" {
		t.Errorf("target project id came from the request body: %q", r.TargetProjectID)
	}
	if r.NewProjectName != testDTORestoredName {
		t.Errorf("newProjectName: got %q, want %q", r.NewProjectName, testDTORestoredName)
	}
}

// A display name is the one piece of naming the caller owns, and it is required.
func TestRestoreRequestRequiresADisplayName(t *testing.T) {
	if err := (RestoreRequest{NewProjectName: testDTORestoredName}).Validate(); err != nil {
		t.Errorf("a named restore must validate: %v", err)
	}
	if err := (RestoreRequest{}).Validate(); err == nil {
		t.Error("a restore without newProjectName must be rejected")
	}
}

// --- ProvisioningResponse JSON ---

func TestProvisioningResponseJSON(t *testing.T) {
	port := 5432
	resp := ProvisioningResponse{
		ProjectID:    "db-1",
		Status:       "ACTIVE",
		CurrentStage: StageCompleted,
		Namespace:    "org1-db-1",
		Host:         "db-1.svc.cluster.local",
		Port:         &port,
		DatabaseName: "myapp",
	}

	b, err := json.Marshal(resp)
	if err != nil {
		t.Fatalf(testDTOMarshalFmt, err)
	}

	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		t.Fatalf(testDTOUnmarshalFmt, err)
	}

	if raw["projectId"] != "db-1" {
		t.Errorf("projectId: got %v", raw["projectId"])
	}
	if raw["status"] != "ACTIVE" {
		t.Errorf("status: got %v", raw["status"])
	}
	if raw["port"] != float64(5432) {
		t.Errorf("port: got %v", raw["port"])
	}
}

// --- CredentialsResponse ---

func TestCredentialsResponseFields(t *testing.T) {
	user := testutil.FixtureToken("user")
	pass := testutil.FixturePassword("creds")
	resp := CredentialsResponse{
		ProjectID:     "p1",
		Host:          "db.local",
		Port:          5432,
		DatabaseName:  "app",
		Username:      user,
		Password:      pass,
		SSLMode:       "require",
		ConnectionURL: fmt.Sprintf("postgresql://%s:%s@db.local:5432/app?sslmode=require", user, pass),
	}

	b, _ := json.Marshal(resp)
	var raw map[string]interface{}
	json.Unmarshal(b, &raw)

	if raw["connectionUrl"] != resp.ConnectionURL {
		t.Errorf("connectionUrl: got %v", raw["connectionUrl"])
	}
	if raw["sslMode"] != "require" {
		t.Errorf("sslMode: got %v", raw["sslMode"])
	}
}

// --- BackupRecord ---

func TestBackupRecordJSON(t *testing.T) {
	rec := BackupRecord{
		ID:        "bk-1",
		ProjectID: "proj-1",
		Timestamp: "2025-01-01T00:00:00Z",
		Type:      "MANUAL",
		Status:    "COMPLETED",
	}
	b, err := json.Marshal(rec)
	if err != nil {
		t.Fatalf(testDTOMarshalFmt, err)
	}
	var got BackupRecord
	if err := json.Unmarshal(b, &got); err != nil {
		t.Fatalf(testDTOUnmarshalFmt, err)
	}
	if got.Type != "MANUAL" {
		t.Errorf("type: got %s", got.Type)
	}
	if got.Status != "COMPLETED" {
		t.Errorf("status: got %s", got.Status)
	}
}

// Both deletion statuses mean a teardown owns the project: the storage door
// and the API gate branch on this, so it has to name exactly those two.
func TestIsDeletionStatus(t *testing.T) {
	for _, status := range []string{"DELETING", "BACKUPS_PENDING_DELETE"} {
		if !IsDeletionStatus(status) {
			t.Errorf("%s should count as a deletion status", status)
		}
	}
	for _, status := range []string{"ACTIVE", "PAUSED", "FAILED", "PROVISIONING", ""} {
		if IsDeletionStatus(status) {
			t.Errorf("%s must not count as a deletion status", status)
		}
	}
}
