package tableimport

import (
	"errors"
	"fmt"
	"strings"

	"github.com/excalibase/provisioning-poc/internal/schema"
)

// Mode is whether an import makes a new table or adds to an existing one.
type Mode string

const (
	ModeCreate Mode = "create"
	ModeAppend Mode = "append"
)

const (
	generatedID     = "id"
	maxNullTokens   = 8
	maxNullTokenLen = 64
)

// ColumnSpec maps one column of the file (by position) to a table column.
// Columns of the file with no spec are skipped.
type ColumnSpec struct {
	Source int        `json:"source"`
	Name   string     `json:"name"`
	Type   ColumnType `json:"type"`
}

// Options is what the user chose in the preview. Every field is checked
// again here; the preview's answer is a suggestion, not a trusted input.
type Options struct {
	Schema     string       `json:"schema"`
	Table      string       `json:"table"`
	Mode       Mode         `json:"mode"`
	HasHeader  bool         `json:"hasHeader"`
	Delimiter  string       `json:"delimiter,omitempty"`
	Sheet      string       `json:"sheet,omitempty"`
	Columns    []ColumnSpec `json:"columns"`
	PrimaryKey string       `json:"primaryKey,omitempty"`
	NullTokens []string     `json:"nullTokens,omitempty"`
}

// Validate refuses anything that could reach SQL unquoted or make the load
// ambiguous.
func (o Options) Validate(lim Limits) error {
	if err := ValidateTargetSchema(o.Schema); err != nil {
		return fmt.Errorf("schema: %w", err)
	}
	if err := ValidateIdentifier(o.Table); err != nil {
		return fmt.Errorf("table: %w", err)
	}
	if o.Mode != ModeCreate && o.Mode != ModeAppend {
		return errors.New(`mode must be "create" or "append"`)
	}
	if len(o.Columns) == 0 {
		return errors.New("choose at least one column to import")
	}
	if err := o.validateColumns(lim); err != nil {
		return err
	}
	if err := o.validatePrimaryKey(); err != nil {
		return err
	}
	return validateNullTokens(o.NullTokens)
}

func (o Options) validateColumns(lim Limits) error {
	names := make(map[string]bool, len(o.Columns))
	sources := make(map[int]bool, len(o.Columns))
	for _, col := range o.Columns {
		if err := ValidateIdentifier(col.Name); err != nil {
			return fmt.Errorf("column: %w", err)
		}
		if _, err := ParseColumnType(string(col.Type)); err != nil {
			return fmt.Errorf("column %s: %w", col.Name, err)
		}
		if col.Source < 0 || col.Source >= lim.MaxColumns {
			return fmt.Errorf("column %s: source position %d is out of range", col.Name, col.Source)
		}
		if names[col.Name] {
			return fmt.Errorf("column %s is named twice", col.Name)
		}
		if sources[col.Source] {
			return fmt.Errorf("file column %d is mapped twice", col.Source+1)
		}
		names[col.Name], sources[col.Source] = true, true
	}
	return nil
}

func (o Options) validatePrimaryKey() error {
	if o.Mode != ModeCreate {
		return nil
	}
	if o.PrimaryKey == "" {
		for _, col := range o.Columns {
			if col.Name == generatedID {
				return errors.New(`a column is named "id": choose it as the primary key or rename it`)
			}
		}
		return nil
	}
	for _, col := range o.Columns {
		if col.Name == o.PrimaryKey {
			return nil
		}
	}
	return fmt.Errorf("primary key %q is not one of the imported columns", o.PrimaryKey)
}

func validateNullTokens(tokens []string) error {
	if len(tokens) > maxNullTokens {
		return fmt.Errorf("at most %d null markers", maxNullTokens)
	}
	for _, token := range tokens {
		if len(token) > maxNullTokenLen {
			return fmt.Errorf("a null marker is longer than %d characters", maxNullTokenLen)
		}
	}
	return nil
}

// Nulls are the cell values stored as NULL; the empty cell by default.
func (o Options) Nulls() []string {
	if len(o.NullTokens) == 0 {
		return []string{""}
	}
	return o.NullTokens
}

// ColumnNames lists the target columns in load order.
func (o Options) ColumnNames() []string {
	names := make([]string, len(o.Columns))
	for i, col := range o.Columns {
		names[i] = col.Name
	}
	return names
}

// CreateTableSQL is the DDL of a validated create. Every identifier is
// quoted and every type comes from the fixed list.
func (o Options) CreateTableSQL() string {
	defs := make([]string, 0, len(o.Columns)+2)
	if o.PrimaryKey == "" {
		defs = append(defs, schema.QuoteIdent(generatedID)+" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
	}
	for _, col := range o.Columns {
		defs = append(defs, schema.QuoteIdent(col.Name)+" "+string(col.Type))
	}
	if o.PrimaryKey != "" {
		defs = append(defs, "PRIMARY KEY ("+schema.QuoteIdent(o.PrimaryKey)+")")
	}
	return "CREATE TABLE " + schema.QuoteIdent(o.Schema) + "." + schema.QuoteIdent(o.Table) +
		" (" + strings.Join(defs, ", ") + ")"
}
