package tableimport

import (
	"strings"
	"testing"
)

func validOptions() Options {
	return Options{
		Schema: "public", Table: "people", Mode: ModeCreate, HasHeader: true,
		Columns: []ColumnSpec{
			{Source: 0, Name: "name", Type: TypeText},
			{Source: 2, Name: "age", Type: TypeInteger},
		},
	}
}

func TestOptions_Valid(t *testing.T) {
	opts := validOptions()
	if err := opts.Validate(testLimits()); err != nil {
		t.Fatal(err)
	}
}

func TestOptions_RefusesUnsafeOrInconsistentInput(t *testing.T) {
	cases := map[string]func(o *Options){
		"quoted table name":   func(o *Options) { o.Table = `people"; DROP TABLE x;--` },
		"upper-case table":    func(o *Options) { o.Table = "People" },
		"platform schema":     func(o *Options) { o.Schema = "excalibase" },
		"catalog schema":      func(o *Options) { o.Schema = "pg_catalog" },
		"unknown mode":        func(o *Options) { o.Mode = "replace" },
		"no columns":          func(o *Options) { o.Columns = nil },
		"bad column name":     func(o *Options) { o.Columns[0].Name = "a b" },
		"duplicate column":    func(o *Options) { o.Columns[1].Name = "name" },
		"unknown type":        func(o *Options) { o.Columns[0].Type = "text; DROP" },
		"negative source":     func(o *Options) { o.Columns[0].Source = -1 },
		"source past the cap": func(o *Options) { o.Columns[0].Source = 20 },
		"same source twice":   func(o *Options) { o.Columns[1].Source = 0 },
		"primary key missing": func(o *Options) { o.PrimaryKey = "nope" },
		"generated id clash":  func(o *Options) { o.Columns[0].Name = "id" },
		"too many null tokens": func(o *Options) {
			o.NullTokens = []string{"a", "b", "c", "d", "e", "f", "g", "h", "i"}
		},
		"long null token": func(o *Options) { o.NullTokens = []string{strings.Repeat("n", 65)} },
	}
	for name, mutate := range cases {
		t.Run(name, func(t *testing.T) {
			opts := validOptions()
			mutate(&opts)
			if err := opts.Validate(testLimits()); err == nil {
				t.Fatal("accepted")
			}
		})
	}
}

func TestOptions_AChosenPrimaryKeyNeedsNoGeneratedID(t *testing.T) {
	opts := validOptions()
	opts.Columns[0].Name = "id"
	opts.PrimaryKey = "id"
	if err := opts.Validate(testLimits()); err != nil {
		t.Fatal(err)
	}
}

func TestCreateTableSQL_QuotesEveryIdentifier(t *testing.T) {
	opts := validOptions()
	got := opts.CreateTableSQL()
	want := `CREATE TABLE "public"."people" ("id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "name" text, "age" integer)`
	if got != want {
		t.Fatalf("got  %s\nwant %s", got, want)
	}
	opts.Columns[0].Name = "code"
	opts.PrimaryKey = "code"
	got = opts.CreateTableSQL()
	want = `CREATE TABLE "public"."people" ("code" text, "age" integer, PRIMARY KEY ("code"))`
	if got != want {
		t.Fatalf("got  %s\nwant %s", got, want)
	}
}

func TestOptions_NullTokenDefaultsToTheEmptyCell(t *testing.T) {
	opts := validOptions()
	if got := opts.Nulls(); len(got) != 1 || got[0] != "" {
		t.Fatalf("nulls = %q", got)
	}
}
